root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o main ."
bin = "main"
pre_cmd = ["npx tailwindcss -i ./pages/layout/input.css -o ./dist/output.css --watch &"]
full_bin = "./main serve"
include_ext = ["go", "tpl", "tmpl", "html", "templ", "gohtml", "css"]
exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules", "pb_data", "main", "dist"]
delay = 400
stop_on_error = true
log = "air_errors.log"
send_interrupt = false

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
