root = "."
tmp_dir = "."

[build]
cmd = "go build -o main ."
bin = "main"
full_bin = "./main serve"
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
